config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'users#welcome' , as: 'home'

  get 'index', to: 'users#index'

  get '/game', to: 'game#index' , as: 'index_game'
  get '/game/play', to: 'game#play'
  get 'test', to: 'users#test'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }
  </style>

  <body>

  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, message| %>
        <div class="alert <%= bootstrap_class_for(name) %>">
          <button class="close" data-dismiss="alert">&times;</button>
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>


  <nav class="site-header sticky-top py-1">
    <div class="container d-flex flex-column flex-md-row justify-content-between">
      <span class="my-0 mr-md-auto font-weight-bold"><%= link_to "Joker" , home_path , class: "nav-link" %></span>
      <% if user_signed_in? %>
        <a class="nav-item">
          <%= link_to "PLAY" , index_game_path , class: "nav-link" %>
        </a>
        <a class="nav-item">
          <%= link_to "SIGN OUT" , destroy_user_session_path , method: :delete , class: "nav-link" %>
        </a>
      <% else %>
        <a class="nav-item">
          <%= link_to "SIGN IN" , new_user_session_path , class: "nav-link" %>
        </a>
        <a class="nav-item">
          <%= link_to "SIGN UP" , new_user_registration_path , class: "nav-link" %>
        </a>
      <% end %>

    </div>
  </nav>

    <%= yield %>
  </body>
</html>